# Site settings
title: studio d'essai
email: stephane@4eb.org.au
description: "International experimental, electronic and free culture on Global Digital."
baseurl: ""
url: "https://studio-dessai.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
plugins:
  - jekyll-redirect-from