# Site settings
title: studio d'essai
email: stephane@4eb.org.au
description: "Electronic music transversing time and space on Global digital."
baseurl: ""
url: "https://studio-dessai.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
