# Site settings
title: studio d'essai
# email: stephane@4eb.org.au
description: "Experimental electronic radio hour on 4eb Brisbane."
baseurl: ""
url: "https://studio-dessai.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
